/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as LocalizacaoRouteImport } from './routes/localizacao'
import { Route as EmitirGruRouteImport } from './routes/emitir-gru'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CertificadoRouteImport } from './routes/certificado'
import { Route as IndexRouteImport } from './routes/index'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalizacaoRoute = LocalizacaoRouteImport.update({
  id: '/localizacao',
  path: '/localizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const EmitirGruRoute = EmitirGruRouteImport.update({
  id: '/emitir-gru',
  path: '/emitir-gru',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificadoRoute = CertificadoRouteImport.update({
  id: '/certificado',
  path: '/certificado',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certificado': typeof CertificadoRoute
  '/contato': typeof ContatoRoute
  '/emitir-gru': typeof EmitirGruRoute
  '/localizacao': typeof LocalizacaoRoute
  '/produtos': typeof ProdutosRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificado': typeof CertificadoRoute
  '/contato': typeof ContatoRoute
  '/emitir-gru': typeof EmitirGruRoute
  '/localizacao': typeof LocalizacaoRoute
  '/produtos': typeof ProdutosRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certificado': typeof CertificadoRoute
  '/contato': typeof ContatoRoute
  '/emitir-gru': typeof EmitirGruRoute
  '/localizacao': typeof LocalizacaoRoute
  '/produtos': typeof ProdutosRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/certificado'
    | '/contato'
    | '/emitir-gru'
    | '/localizacao'
    | '/produtos'
    | '/servicos'
    | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/certificado'
    | '/contato'
    | '/emitir-gru'
    | '/localizacao'
    | '/produtos'
    | '/servicos'
    | '/sobre'
  id:
    | '__root__'
    | '/'
    | '/certificado'
    | '/contato'
    | '/emitir-gru'
    | '/localizacao'
    | '/produtos'
    | '/servicos'
    | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertificadoRoute: typeof CertificadoRoute
  ContatoRoute: typeof ContatoRoute
  EmitirGruRoute: typeof EmitirGruRoute
  LocalizacaoRoute: typeof LocalizacaoRoute
  ProdutosRoute: typeof ProdutosRoute
  ServicosRoute: typeof ServicosRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/localizacao': {
      id: '/localizacao'
      path: '/localizacao'
      fullPath: '/localizacao'
      preLoaderRoute: typeof LocalizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emitir-gru': {
      id: '/emitir-gru'
      path: '/emitir-gru'
      fullPath: '/emitir-gru'
      preLoaderRoute: typeof EmitirGruRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificado': {
      id: '/certificado'
      path: '/certificado'
      fullPath: '/certificado'
      preLoaderRoute: typeof CertificadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertificadoRoute: CertificadoRoute,
  ContatoRoute: ContatoRoute,
  EmitirGruRoute: EmitirGruRoute,
  LocalizacaoRoute: LocalizacaoRoute,
  ProdutosRoute: ProdutosRoute,
  ServicosRoute: ServicosRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
